DEMOSTRACIÓN DE CONOCIMIENTOS SOBRE MACHINE LEARNING.
**texto en negrita**

---



La idea de este ejercicio es lograr una oportunidad laboral para seguir creciendo en este tema.

***By Carlos Manuel Patiño Machado.***

Escribí la clase NeuralNetwork con muy poco código googleado. La adaptación es 100% escrita por mí. 

Aplicar la IA no es solamente copiar y pegar código usando un Framework a ciegas, sin antes analizar la calidad de los datos de entrenamiento y buscar la mejor arquitectura de red de validación para el correcto entretamiento.

Además el ajuste de la red y la debida optimización coste/beneficio del entrenamiento fué ajustado utilizando diversas teorías que explica AndrewNG en Coursera.

En este notebook demuestro mis conocimientos sobre Perceptrones, al mismo tiempo que Machine Learning y sobre todo Redes Neuronales, para IA (entrenamiento automático). 

Como es posible verse no se utiliza ningún framework conocido para IA como Tensorflow, o scikit etc.

Salvo que si se usan Numpy para hacer operaciones de Array una vez la lógica del perceptron y su Backpropagation fué claramente estudiado en los ejercicios "Neuro" de mi repositorio. 

Intenté escribir este ejercicio con solo operaciones matemáticas pero; es totalmente inútil por la lentitud sobre todo si la red se entrena para identificar patrones en imagenes. De modo que este ejercicio si que utiliza Nummpy para realizar operaciones matriciales.

El próximo pasó es gráficar la Learning Curve Q. Y tal vez hacer un file uploader para que cualquier usuario común suba la foto de un perro o gato y testee con su propia imagen y no con la colección aca presente.

**En ocasiones la red es >95%  efectiva. Tieniendo como limitantes la detección de perros estilo dibujo animado ya que la red fué entrenada usando fotos de perros reales... Sin embargo sería un hito ya que un niño si que es capaz de identiicar un canino en dibujos animados una vez aprende que es un perro en la vida real.** 

Espero resolver esto prontamente. 


In [ ]:
import sys
import copy
import random
import numpy as np 
import math as math
import planar_utils
import time
from neural_network import NeuralNetwork
from os import listdir
from PIL import Image as PImage
from PIL import ImageOps as ImageOps
import glob
import os

In [23]:
def parse_file(file):
 
    img = PImage.open(file)
    size= (64, 64)
    img.thumbnail(size)
    img = ImageOps.fit(img,size , PImage.ANTIALIAS)
    npImage=np.array(img, np.uint16)
    img_size = npImage.shape
    return npImage

In [24]:
def load_images_from_folder(folder, quantity):
    images = []
    for filename in os.listdir(folder)[:quantity]:        
        images.append(parse_file(folder+filename))
    return images

In [25]:
windows_path = '/content/neuron/'

In [26]:
dataset_cats = load_images_from_folder(windows_path+'cat/',200)
testset_cats = np.array(dataset_cats)[101:200]
dataset_cats = np.array(dataset_cats)[:100]

print(dataset_cats[0].shape)

(64, 64, 3)


In [27]:
dataset_dogs = load_images_from_folder(windows_path+'dog/',200)
testset_dogs = np.array(dataset_dogs)[101:200]
dataset_dogs = np.array(dataset_dogs)[:100]

print(dataset_dogs.shape)

(100, 64, 64, 3)


In [28]:
samples_size = dataset_dogs.shape[0]
train_x_cats = (dataset_cats.reshape(samples_size, -1)) /255.
train_x_dogs = (dataset_dogs.reshape(samples_size, -1)) /255.
dataset_full = (np.concatenate((train_x_cats, train_x_dogs)))
train_x_full = dataset_full
#print(dataset_cats[0][0])
print(train_x_cats[0])

print(train_x_full.shape)

[0.14117647 0.14509804 0.09019608 ... 0.17254902 0.15686275 0.1254902 ]
(200, 12288)


In [29]:
samples_size = testset_dogs.shape[0]
test_x_cats = (testset_cats.reshape(samples_size, -1)) /255.
test_x_dogs = (testset_dogs.reshape(samples_size, -1)) /255.
testset_full = (np.concatenate((test_x_cats, test_x_dogs)))
test_x_full = testset_full
#print(dataset_cats[0][0])
print(test_x_cats[0])

print(test_x_full.shape)

[0.53333333 0.57647059 0.58823529 ... 0.56078431 0.3254902  0.29411765]
(198, 12288)


In [36]:
X = train_x_full

Y_cats = np.ones((1,train_x_cats.shape[0]))
Y_dogs = np.zeros((1,train_x_cats.shape[0]))
Y_full = np.array([np.concatenate((Y_cats[0], Y_dogs[0]))]).T

nn = NeuralNetwork(X, Y_full, 32, 'tanh')
parameters = nn.get_parameters()
print(parameters)
Y = Y_full

#print(Y_full.shape)

{'W1': array([[-0.00375192, -0.00079266,  0.0069811 , ..., -0.00167024,
         0.01877226, -0.01668275],
       [ 0.02659275, -0.0171964 , -0.00833737, ...,  0.00050015,
         0.01164004,  0.00493056],
       [ 0.00204444, -0.01057339,  0.00913258, ...,  0.01434511,
         0.00849272,  0.01120601],
       ...,
       [-0.00143755,  0.00762541,  0.00995856, ..., -0.00092361,
        -0.00286854,  0.00122921],
       [-0.00633691, -0.00800978, -0.01431786, ...,  0.01055499,
        -0.01269393, -0.00291663],
       [-0.00476078, -0.00688102, -0.01459654, ..., -0.00244687,
         0.02311477,  0.00522732]]), 'b1': array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0

In [31]:
#test demo binary
#X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
#Y = np.array([[1], [0.1], [0.5], [0]])
#nn = NeuralNetwork(X, Y, 8, 'sigmoid')
#parameters = nn.get_parameters()
#print(parameters)
#print(X.shape) #(4, 2)
#print(Y.shape) #(4, 1)

{'W1': array([[ 1.36602230e-02,  8.40109244e-03],
       [ 9.91756970e-04, -6.95139994e-03],
       [ 1.79856612e-03,  1.06587862e-02],
       [-1.02737378e-02,  6.12251630e-03],
       [-5.11040687e-03,  2.55858364e-05],
       [-1.20426637e-02, -1.31778670e-02],
       [-6.81823562e-03, -5.70104881e-03],
       [-5.09258080e-05, -1.41975840e-03]]), 'b1': array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]]), 'W2': array([[-0.00110836,  0.02295179, -0.00699105, -0.0032956 ,  0.00033164,
        -0.00951283,  0.01215147, -0.00081221]]), 'b2': array([[0.]]), 'mode': 'sigmoid'}
(4, 2)
(4, 1)


In [37]:
print(X.shape) #(4, 2)
start_time = time.time()
info = nn.trainer(10000, 0.01, X.T, Y.T, log=False)
elapsed_time = time.time() - start_time
print('elapsed_time: ', elapsed_time)

(200, 12288)
elapsed_time:  209.30662417411804


In [38]:
Xt_true = train_x_cats
id_cat = 99
print(Xt_true[id_cat:id_cat+1].shape)
print(Xt_true[id_cat:id_cat+1])
t = nn.test(Xt_true[id_cat:id_cat+1].T)
print('t: ', t)
accy =  Y[id_cat:id_cat+1] /  t[0] 
print('accy: ',(accy))


(1, 12288)
[[0.83529412 0.85490196 0.81568627 ... 0.84705882 0.82745098 0.81176471]]
t:  [[0.9873053]]
accy:  [[1.01285793]]


In [39]:
Xt_false = train_x_dogs
id_dog = 99
print(Xt_false[id_dog:id_dog+1].shape)
print(Xt_false[id_dog:id_dog+1])
t = nn.test(Xt_false[id_dog:id_dog+1].T)
print('t: ', t)
accy =  Y[id_dog:id_dog+1] /  t[0] 
print('accy: ',(accy))

(1, 12288)
[[0.53333333 0.54901961 0.55294118 ... 0.58039216 0.60392157 0.59607843]]
t:  [[0.00214636]]
accy:  [[465.90609175]]


In [40]:
print(X[0])

print(Xt_false[0])

[0.14117647 0.14509804 0.09019608 ... 0.17254902 0.15686275 0.1254902 ]
[0.19215686 0.18823529 0.17254902 ... 0.49803922 0.36862745 0.2745098 ]


In [41]:
#Prueba data de entrenamiento
cats_count = 0
dogs_count = 0
for xx in range(0,X.shape[0]):
    t = nn.test(X[xx:xx+1].T)
    #print(t[0][0], xx)
    y_h = t[0][0]
    if(y_h>0.8):
        cats_count = cats_count +1
    else:
        dogs_count = dogs_count +1

print('cats detected: ', cats_count)
print('dogs detected: ', dogs_count)

cats detected:  100
dogs detected:  100


In [42]:
#Prueba data de validacin 
cats_count = 0
dogs_count = 0
X_test = test_x_full
for xx in range(0,X_test.shape[0]):
    t = nn.test(X_test[xx:xx+1].T)
    #print(t[0][0], xx)
    y_h = t[0][0]
    if(y_h>0.8):
        cats_count = cats_count +1
    else:
        dogs_count = dogs_count +1

print('cats validateds: ', cats_count)
print('dogs validateds: ', dogs_count)

cats validateds:  107
dogs validateds:  91


In [44]:
#Xt = np.random.randn(1,65536)
#print(Xt.shape)
#t = nn.test(Xt.T)
#print('t: ', t)
#accy =  np.sum(Y[:1]) / (np.sum(t) )
#print('accy: ',(accy))

In [45]:
#test demo binary
print(X.shape)
print(X[:1])
t = nn.test(X.T)
print('t: ', t)
accy =  np.sum(Y) / (np.sum(t) )
print('accy: ',(accy))

(200, 12288)
[[0.14117647 0.14509804 0.09019608 ... 0.17254902 0.15686275 0.1254902 ]]
t:  [[ 0.99358507  0.9550254   0.99393712  0.93494235  0.93296128  0.93004762
   0.9778776   0.99578049  0.99055887  0.99158166  0.97237868  0.99593949
   0.99449251  0.97668594  0.98124308  0.99675189  0.94511281  0.99053068
   0.95813055  0.97073333  0.98087172  0.98062664  0.91769079  0.97454624
   0.98897721  0.9982048   0.97867293  0.99240091  0.98491037  0.98492873
   0.96681609  0.9858443   0.97350252  0.99848275  0.93450131  0.98837891
   0.99541226  0.91458543  0.97496123  0.9728089   0.87710611  0.90358732
   0.96205077  0.92764445  0.99700236  0.99244378  0.99615094  0.92098332
   0.94902309  0.96457174  0.99004354  0.94774258  0.95018405  0.99031424
   0.99304626  0.91402239  0.99715436  0.98021828  0.97260308  0.96136863
   0.95288515  0.96053099  0.91796733  0.99301631  0.95885897  0.9482127
   0.99109099  0.98729219  0.95323341  0.99523352  0.98034065  0.99469997
   0.96074422  0.93618

In [53]:
#probar coleccion que ya no existe en el dataset
image_test = load_images_from_folder(windows_path+'tests/',3)

testset_user = np.array(image_test)
samples_size = testset_user.shape[0]
test_flatten = (testset_user.reshape(samples_size, -1)) /255.


t = nn.test(test_flatten.T)
print('t: ', t)


t:  [[0.94140395 0.4626263  0.24704403]]


In [55]:
#probar coleccion que ya no existe en el dataset
images = []
images.append(parse_file(windows_path+'/tests/perro-carlos.jpg'))

image_test = images
testset_user = np.array(image_test)
samples_size = testset_user.shape[0]
test_flatten = (testset_user.reshape(samples_size, -1)) /255.


t = nn.test(test_flatten.T)
if t>0.8:
    print('Its a cat!!')
else:
    print('Its a dog!!')
print('t: ', t)

Its a dog!!
t:  [[0.38619416]]
