In [20]:
#Compuerta analogica.
#Version de neuronas vectorizadas con numpy
import sys
import copy
import random
import numpy as np 
import math as math
import utils
import time
from neural_network import NeuralNetwork
from os import listdir
from PIL import Image as PImage
from PIL import ImageOps as ImageOps
import glob
import os

In [21]:
def parse_file(file):
 
    img = PImage.open(file)
    size= (64, 64)
    img.thumbnail(size)
    img = ImageOps.fit(img,size , PImage.ANTIALIAS)
    npImage=np.array(img, np.uint16)
    img_size = npImage.shape
    return npImage

In [22]:
def load_images_from_folder(folder, quantity):
    images = []
    for filename in os.listdir(folder)[:quantity]:        
        images.append(parse_file(folder+filename))
    return images

In [23]:
windows_path = 'C:/Users/carlos/OneDrive/machine_learning/nn/'

In [24]:
dataset_cats = load_images_from_folder(windows_path+'cat/',200)
testset_cats = np.array(dataset_cats)[101:200]
dataset_cats = np.array(dataset_cats)[:100]

print(dataset_cats[0].shape)

(64, 64, 3)


In [25]:
dataset_dogs = load_images_from_folder(windows_path+'dog/',200)
testset_dogs = np.array(dataset_dogs)[101:200]
dataset_dogs = np.array(dataset_dogs)[:100]

print(dataset_dogs.shape)

(100, 64, 64, 3)


In [26]:
samples_size = dataset_dogs.shape[0]
train_x_cats = (dataset_cats.reshape(samples_size, -1)) /255.
train_x_dogs = (dataset_dogs.reshape(samples_size, -1)) /255.
dataset_full = (np.concatenate((train_x_cats, train_x_dogs)))
train_x_full = dataset_full
#print(dataset_cats[0][0])
print(train_x_cats[0])

print(train_x_full.shape)

[0.95686275 0.78823529 0.47843137 ... 0.03137255 0.03137255 0.00392157]
(200, 12288)


In [27]:
samples_size = testset_dogs.shape[0]
test_x_cats = (testset_cats.reshape(samples_size, -1)) /255.
test_x_dogs = (testset_dogs.reshape(samples_size, -1)) /255.
testset_full = (np.concatenate((test_x_cats, test_x_dogs)))
test_x_full = testset_full
#print(dataset_cats[0][0])
print(test_x_cats[0])

print(test_x_full.shape)

[0.42352941 0.38431373 0.34509804 ... 0.71372549 0.6745098  0.63921569]
(198, 12288)


In [29]:
X = train_x_full

Y_cats = np.ones((1,train_x_cats.shape[0]))
Y_dogs = np.zeros((1,train_x_cats.shape[0]))
Y_full = np.array([np.concatenate((Y_cats[0], Y_dogs[0]))]).T

nn = NeuralNetwork(X, Y_full, 32, 'tanh')
parameters = nn.get_parameters()
print(parameters)
Y = Y_full

#print(Y_full.shape)

{'W1': array([[-0.00499799, -0.00481926,  0.00895438, ..., -0.01793775,
        -0.00645417,  0.00454576],
       [ 0.00218608, -0.00919006, -0.00285732, ...,  0.00972544,
         0.00249854, -0.01982253],
       [ 0.00228624,  0.00761571, -0.0025751 , ...,  0.00410515,
         0.00049976,  0.00388288],
       ...,
       [-0.00488772, -0.01759325, -0.00017839, ...,  0.00535541,
         0.00039157, -0.00540717],
       [ 0.01548829,  0.00485395,  0.00261907, ...,  0.02239123,
         0.00364679,  0.00977518],
       [ 0.0135845 , -0.00054091,  0.01137464, ..., -0.01525848,
         0.00351213, -0.00244069]]), 'b1': array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0

In [10]:
#test demo binary
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[1], [0.1], [0.5], [0]])
nn = NeuralNetwork(X, Y, 8, 'sigmoid')
parameters = nn.get_parameters()
print(parameters)
print(X.shape) #(4, 2)
print(Y.shape) #(4, 1)

{'W1': array([[ 7.17420128e-03,  3.80045858e-04],
       [-3.49464082e-03, -1.45922147e-02],
       [ 9.43282158e-03, -1.33692679e-02],
       [-4.06610955e-03,  8.70988020e-03],
       [ 9.68337798e-05, -3.35723209e-03],
       [ 2.00066578e-03,  1.07187092e-02],
       [-1.96141395e-02,  1.16825839e-03],
       [-1.79498725e-02, -7.61879280e-04]]), 'b1': array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]]), 'W2': array([[ 0.01248717,  0.00328874,  0.00241094,  0.00470991, -0.0115771 ,
        -0.01325555,  0.01441751,  0.00228298]]), 'b2': array([[0.]]), 'mode': 'sigmoid'}
(4, 2)
(4, 1)


In [30]:
print(X.shape) #(4, 2)
start_time = time.time()
info = nn.trainer(10000, 0.01, X.T, Y.T, log=False)
elapsed_time = time.time() - start_time
print('elapsed_time: ', elapsed_time)

(200, 12288)
elapsed_time:  181.41337966918945


In [31]:
Xt_true = train_x_cats
id_cat = 99
print(Xt_true[id_cat:id_cat+1].shape)
print(Xt_true[id_cat:id_cat+1])
t = nn.test(Xt_true[id_cat:id_cat+1].T)
print('t: ', t)
accy =  Y[id_cat:id_cat+1] /  t[0] 
print('accy: ',(accy))


(1, 12288)
[[0.90980392 0.91764706 0.90588235 ... 0.67058824 0.71372549 0.74117647]]
t:  [[0.96918529]]
accy:  [[1.03179444]]


In [13]:
Xt_false = train_x_dogs
id_dog = 99
print(Xt_false[id_dog:id_dog+1].shape)
print(Xt_false[id_dog:id_dog+1])
t = nn.test(Xt_false[id_dog:id_dog+1].T)
print('t: ', t)
accy =  Y[id_dog:id_dog+1] /  t[0] 
print('accy: ',(accy))

(1, 12288)
[[1.         1.         1.         ... 0.84313725 0.88235294 0.89019608]]


ValueError: shapes (8,2) and (12288,1) not aligned: 2 (dim 1) != 12288 (dim 0)

In [32]:
print(X[0])

print(Xt_false[0])

[0.95686275 0.78823529 0.47843137 ... 0.03137255 0.03137255 0.00392157]
[0.56078431 0.54509804 0.6        ... 0.29803922 0.3372549  0.34509804]


In [33]:
#Prueba data de entrenamiento
cats_count = 0
dogs_count = 0
for xx in range(0,X.shape[0]):
    t = nn.test(X[xx:xx+1].T)
    #print(t[0][0], xx)
    y_h = t[0][0]
    if(y_h>0.8):
        cats_count = cats_count +1
    else:
        dogs_count = dogs_count +1

print('cats detected: ', cats_count)
print('dogs detected: ', dogs_count)

cats detected:  100
dogs detected:  100


In [34]:
#Prueba data de validacin 
cats_count = 0
dogs_count = 0
X_test = test_x_full
for xx in range(0,X_test.shape[0]):
    t = nn.test(X_test[xx:xx+1].T)
    #print(t[0][0], xx)
    y_h = t[0][0]
    if(y_h>0.8):
        cats_count = cats_count +1
    else:
        dogs_count = dogs_count +1

print('cats validateds: ', cats_count)
print('dogs validateds: ', dogs_count)

cats validateds:  113
dogs validateds:  85


In [35]:
Xt = np.random.randn(1,65536)
print(Xt.shape)
t = nn.test(Xt.T)
print('t: ', t)
accy =  np.sum(Y[:1]) / (np.sum(t) )
print('accy: ',(accy))

(1, 65536)


ValueError: shapes (32,12288) and (65536,1) not aligned: 12288 (dim 1) != 65536 (dim 0)

In [18]:
#test demo binary
print(X.shape)
print(X[:1])
t = nn.test(X.T)
print('t: ', t)
accy =  np.sum(Y) / (np.sum(t) )
print('accy: ',(accy))

(4, 2)
[[0 0]]
t:  [[0.40243385 0.39997384 0.40131432 0.39885828]]
accy:  0.9983899152428534


In [36]:
#probar coleccion que ya no existe en el dataset
image_test = load_images_from_folder(windows_path+'tests/',6)
testset_user = np.array(image_test)
samples_size = testset_user.shape[0]
test_flatten = (testset_user.reshape(samples_size, -1)) /255.


t = nn.test(test_flatten.T)
print('t: ', t)


t:  [[0.48491401 0.99935115 0.97188511 0.74268968 0.607718   0.71210771]]


In [37]:
#probar coleccion que ya no existe en el dataset
images = []
images.append(parse_file(windows_path+'/tests/perro.jpg'))

image_test = images
testset_user = np.array(image_test)
samples_size = testset_user.shape[0]
test_flatten = (testset_user.reshape(samples_size, -1)) /255.


t = nn.test(test_flatten.T)
if t>0.8:
    print('Its a cat!!')
else:
    print('Its a dog!!')
print('t: ', t)

Its a cat!!
t:  [[0.99559224]]
